version: 2.1

# we will test the use of an orb & runner resource-class for this namespace

orbs:
  greeting: kelvintaywl-cci/greeting@1.0.0

executors:
  lightsail-from-transferred:
    machine: true
    resource_class: kelvintaywl-cci/lightsail-medium
  lightsail-original:
    machine: true
    resource_class: kelvintaywl/lightsail-medium
  alpine:
    docker:
      - image: alpine:latest
    resource_class: small

jobs:
  use-orb:
    executor: alpine
    steps:
      - greeting/greet:
          to: stranger
  use-runner:
    parameters:
      exec:
        type: executor
    executor: << parameters.exec >>
    steps:
      - greeting/greet:
          to: stranger

workflows:
  test:
    jobs:
      - use-orb
      - use-runner:
          matrix:
            exec:
              - lightsail-from-transferred
              - lightsail-original
